language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rishi24/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rishi24/docker-react npm run test